# This is a straight port (shit, even including variable names!) of the JS HYS generator found at http://ifyoulikeitsomuchwhydontyougolivethere.com/the-twat-o-tron/
# Obviously absolutely no effort went into making it readable/better.
# Arrays stored here, might move out for readabilities sake but, who cares!
from util import hook
import random

opening1 = [
    "This is just typical",
    "Oh here we go again",
    "this post will probably be deleted. ",
    "I think we all know whats going on here. ",
    "I read about this in the Daily Mail",
    "Typical Nu-Labour arrogance",
    "Oh god not this again.",
    "Mark my words.",
    "I can't believe where this country is headed.",
    "Gordon brown still it at i see",
    "No!!..",
    "Stupid question",
    "Is this what the BBC licence tax gets spent on??",
    "Unbelievable, BBC left-leaning bias again.",
    "This just shows us the BBC's real agenda.",
    "Whites being descriminated against again.",
    "Oh look",
    "I am very angry about this.",
    "publish this if you dare",
    "Lies damn lies and stistics!",
    "FYI",
    "First things first",
    "This tired old question again",
    "Typical BBC..",
    "I don't believe the responses on here..",
    "Aw diddums",
    "It makes me sick",
    "Sad but true",
    "Is this not the BRITISH Broadcasting Corporation",
    "Its simple",
    "Another example of ripoff Britain!",
    "Question",
    "Let's see now",
    "Hear me out",
    "Typical",
    "It's sad but true",
    "global warming, climate change, no such thing, its just another TAX.",
    "Twas ever thus"]

opening2 = [
    "I heard this week that",
    "I read that",
    "studies show that",
    "did you know that",
    "I couldn't care less but ",
    "its the ethnic minorities, gays and lesbians complaining again.",
    "when will people realise that",
    "IMO",
    "in my opinion",
    "does anyone realise that",
    "Open your eyes people!",
    "I'm not being racist but",
    "here come the pc brigade and the nanny state! ",
    "it's obvious that",
    "everyone knows",
    "the media won't admit that",
    "all right-thinking people know that",
    "it's not politically correct to say so but",
    "can't you see that",
    "the bbc pretends it's not true but",
    "I have been realising over the past few years that",
    "I read in the Sun that"
    ]

hated_object = [
    "im sick of the bloody liberal lefty whingers who are",
    "This country is overflowing with illegal immigrants, even the local chippy is run by poles. They are",
    "pedophiles are",
    "paedos are",
    "Gordon Brown is",
    "Nu-Labour is",
    "New Labour is",
    "Labour is",
    "migrants are",
    "immigrants are",
    "black people are",
    "Obama is",
    "Hillary Clinton is",
    "the British sheeple are",
    "modern britain is",
    "the PC Nazis are",
    "the nanny state is",
    "the establishment is",
    "enviro-marxist do-gooders are",
    "hybrid embryos are",
    "this communist government are",
    "Iran is",
    "Iraq is",
    "the UN is",
    "scientists are",
    "communists are",
    "communist facists are",
    "the EU is",
    "French farmers are",
    "Asylum seekers are",
    "pathetic liberal tree huggers are",
    "liberals are",
    "the human rights brigade are",
    "pregnant children are",
    "the permissive society is",
    "ethnics are",
    "illegals are",
    "the Lib Dems are",
    "liberal hand-wringers are",
    "evironazis are",
    "The EU will soon be",
    "EnviroMENTALists are",
    "the Loony Left is",
    "chavs are",
    "non-christians are",
    "Muslims are",
    "pc liberalists are",
    "Arabs are",
    "the Chinese are",
    "the tax-man is",
    "criminals are",
    "namby pamby environmentalists are",
    "the disrespectful youth of today is",
    "prison inmates are",
    "drug scum are",
    "sandal-wearing liberals are",
    "the bastions of political correctness are",
    "Prince Phillip is",
    "those morons in the government are",
    "every single prisoner in Britain is",
    "so-called celebrities are",
    "the Scottish are",
    "all parties except the BNP are",
    "Homosexuals are",
    "knife gangs are",
    "women are",
    "single mothers are",
    "kids today are",
    "Africa is",
    "teenage gangs are",
    "Guardian readers are",
    "Daily Mail readers are",
    "non-taxpayers are",
    "pathetic liberal institutions are",
    "criminal gangs are",
    "we are being brainwashed into",
    "council estate scum are",
    "islamofacists are",
    "soft-touch Britain is",
    "benefits cheats are"
    ]

terrible_thing = [
     "bending over backwards for the ethnic minorities in a white country",
    "taking over the government",
    "raping our kids",
    "killing our kids",
    "going to put us all in Death Camps",
    "putting flouride in our drinking water",
    "destroying our once great country",
    "getting tax-payers money",
    "dumbing us down",
    "run by communists",
    "promoting yob culture",
    "trying to 'save the planet' again",
    "sponging off the taxpayer",
    "allowing us to be swamped",
    "telling us what to do",
    "sexualising our children",
    "selling us short",
    "raising petrol prices",
    "denying our freedoms",
    "introducing more stealth taxes",
    "opening our borders",
    "ruining Great Britain",
    "helping their scottish comrades",
    "playing the race card",
    "peddling their lies",
    "getting rich off the hard working population",
    "selling Britain to the French",
    "meddling in our lives",
    "hugging hoodies",
    "always complaining",
    "getting away with murder",
    "running scared",
    "too namby pamby",
    "terrorising our streets",
    "trying to control our lives",
    "encouraging terrorists",
    "helping al-qaeda",
    "preaching hate",
    "building mosks on every corner",
    "banning nursery rhymes",
    "making it illegal to be patriotic",
    "interfering in our lives again",
    "betraying our freedoms",
    "using history to criticise the pope",
    "inviting in paedophiles and AIDs",
    "pandering to ethnics and gays",
    "getting away with murder",
    "getting away scott free",
    "giving way to multiculturalism",
    "preaching hate",
    "promoting homosexualism",
    "promoting pedofilia",
    "welcoming criminals with open arms",
    "promoting teenage pregnancy",
    "making our streets unsafe",
    "turning Britain into Britainistan",
    "turning prison into a holidaycamp",
    "pandering to minorities",
    "selling us down the river",
    "just helping their cronies",
    "lining their pockets",
    "ignoring the silent majority",
    "giving priority to immigrants",
    "too 'softly softly'",
    "taxing us",
    "giving away are rights to health tourists",
    "making England a Muslim State",
    "getting freebies",
    "stealing my cartax",
    "islamifying the countryside",
    "using my wheelie bin",
    "giving money to their cronies",
    "trying to kill us all",
    "selling us out",
    "trying to bring in legislation to allow gays to get married",
    "destroying our heritage",
    "turning our kids gay",
    "taking our country away from us"
    ]

because = [
    "they hate the British people",
    "it's politically correct",
    "the country is full.",
    "they are foreign and it's what they do",
    "they have been incompetent since day 1",
    "of terrorists",
    "they are barely human",
    "of nu-liar-bore incompetence",
    "of their so-called 'human rights'",
    "they've allowed immigration to go unchecked.",
    "they want to turn Britain into an islamic state.",
    "they want to destroy us from within!",
    "our culture has been emasculated",
    "our country is full already",
    "they are pandering to foreign interests",
    "they are trying to destroy us",
    "the EU now controls this country",
    "they are building an EU superstate",
    "they have given away our sovriegnty",
    "they are trying to cover up their mistakes",
    "this country is no longer ours",
    "Britain is no longer great",
    "they government is lying to us",
    "they are socialists",
    "they are anti-american",
    "they are communists in disguise",
    "they hate our freedoms",
    "Gordon is too busy lining his pockets",
    "of Gordon Brown",
    "they're ruining Britain",
    "I am now ashamed of Britain",
    "the scottish mafia is running the country",
    "muslims are running the show",
    "Britain is now under sharia law",
    "they want to breed a hybrid fetus",
    "they want to destroy the world",
    "they are clinically insane",
    "nobody has the guts to stand up to them",
    "people are too scared to stop them",
    "they are sick",
    "they are traitors"
]

imperative = [
    "We must",
    "Every British working man must",
    "It is vital that we",
    "Read my lips: ",
    "Come on",
    "True patriots must",
    "All Englishmen should",
    "Time to act: ",
    "The silent majority must ",
    "End this madness now, ",
    "Soon we will",
    "Somebody should",
    "The only solution is to",
    "Isn't it obvious?",
    "A wise man once said",
    "Mark my words",
    "It's time we",
    "when will Gordon",
    "when will this government",
    "Wake up people!",
    "Simple answer: ",
    "All true brits should",
    "[number] words:"
]

moronic_solution = [
    "chop their hand's off, see how they like it",
    "bring back flogging and the death penalty i say",
    "bring back the cane, thatll teach em",
    "Send them all back were they came from",
    "get out of the eu and get our country back!!",
    "build more prisons, lock em up and throw away the key",
    "bring back hanging",
    "send them packing",
    "bring back the cane",
    "bring back Churchill",
    "send them to Iraq",
    "bring back Hitler",
    "bring back Mary Whitehouse",
    "bring back Enoch Powell",
    "bring back national service",
    "string them all up",
    "abolish tax",
    "burn them alive",
    "get rid of them",
    "put them in solitary for the next 100 years",
    "run them out of the country",
    "sterolise them all",
    "get tough",
    "send them back where they came from",
    "riot in the streets",
    "rise up against them",
    "smash the system",
    "BAN immoral TV",
    "vote BNP",
    "go round their houses with a pair of pliers and a can of petrol",
    "let Boris Johnson sort it out",
    "call in the army now",
    "shoot on sight",
    "lock our kids away to save them",
    "shut up and obey orders, says the government",
    "round them all up and lock them away",
    "close the borders now",
    "elect Kilroy now",
    "make sure there are consequences",
    "have two strikes and you're out",
    "introduce zero tolerance",
    "promote marriage",
    "make sure everyone knows",
    "say enough is enough",
    "stand up and be counted",
    "ban them all",
    "have another war",
    "elect Jeremy Clarkson as prime minister",
    "speak English",
    "elect Boris Johnson as prime minister",
    "stop taking it lying down",
    "use napalm",
    "put them in loony bin",
    "leave the country.",
    "carpet bomb them flat",
    "put them in a rocket and fire them in to the sun",
    "nuke them"
]

signoff = [
        "Next we'll have pedofiles teaching our kids to swim",
        "No doubt this is legal under the eu human rights act",
        "No doubt this is illegal under the eu human rights act",
        "Soon this country will be majority muslim with a mosk in every village!!!",
        "This is a Christian country we must all have christian values",
        "If you like it so much why dont you go live there",
        "Time to get nu-liar-bore OUT!!!!",
        "Im voting BNP in the next election, its the sensible choice",
        "It could only get worse if the french start coming over!!!",
        "never did me any harm",
        "Pathetic",
        "Simple",
        "Its disgusting",
        "Disgraceful",
        "It's all Browns fault",
        "LOL",
        "Sad but true",
        "BNP for England",
        "We need another war",
        "PS If you are offended by this then leave the country",
        "You couldn't make it up",
        "IT IS HELL ON EARTH, PEOPLE!",
        "WHAT A SHAME!",
        "Its like a nightmare but real",
        "This sounds totally crazy, but it is sadly, probably true",
        "What ever happened to putting UK first?",
        "GREAT britain is going to the dogs",
        "Diana was murdered",
        "This is why I'm emigrating soon",
        "Best thing for them",
        "I'd leave if I had my own country to go back to",
        "It's that simple",
        "It's not rocket science",
        "England for the English",
        "The last to leave, please turn out the light",
        "Shame on you BBC",
        "Cry 'God for Harry, England, and Saint George'",
        "BRITISH FIRST",
        "Need I say more",
        "If you disagree SHUT UP",
        "Is it a tune too familiar from our media?",
        "We need less emotion and more backbone in this country",
        "Next question.",
        "What about OUR rights?",
        "What a mess",
        "These are worrying times",
        "This is very disturbing to me",
        "Wake up, people",
        "Lies! Lies! Lies!",
        "This is probably the best solution all around",
        "Common sense AT LAST!",
        "Nothing will ever change",
        "This is communism folks!",
        "Honestly this country !",
        "Sick to the back teeth",
        "We are all being had here",
        "That would certainly cause a bit more care to be taken",
        "This morning at breakfast my son leaned over to me and in a hushed voice said \"Dad, we are still in England, aren't we?\" No son, I said. Not any more",
        "I am furious about this",
        "This is a perfect idea",
        "It's political correctness gone mad",
        "Oh wait, but what about their 'human rights'",
        "What about my right not to be murdered?",
        "What about my right not to be killed every day?",
        "Oh wait, that would be too sensible",
        "Oh wait, that wouldn't be 'PC' enough",
        "This is never mentioned by the media",
        "what's it going to be - only you can choose",
        "Simple as",
        "Put that in your pipe and smoke it",
        "This worries me",
        "Next",
        "Next stop HELL ON EARTH",
        "Hell in a handcart",
        "What a load of rot",
        "Next stop CHAOS",
        "Next stop WAR",
        "You heard it here first",
        "What would Churchill say?",
        "It's time to revolt people",
        "WHos fault is that?",
        "Lets do what the french do and all strike",
        "Mrs Thatcher must be spinning in her grave",
        "What next? Encourage single-parenting? Oops. They do it already",
        "What next? Allowing in foreigners? Oops. They do it already",
        "What next? Welcoming foreign criminals? Oops. They do it already",
        "What next? Banning Baa Baa Black Sheep? Oops. They do it already",
        "What next? Letting paedos out of jail? Oops. They do it already",
        "What next? Giving benefits out willy-nilly? Oops. They do it already",
        "What happened to GREAT Britain?",
        "No joke",
        "FACT!",
        "What a tragedy",
        "This is Communism folks...",
        "This is GREAT Britain... Lets show it...",
        "Publish this one if you dare",
        "What do you think?",
        "Anybody on the other hand, who wants to have a relationship with a child, ought to be exterminated",
        "I am now repudiating liberalism as I see it as deeply harmful to society",
        "This is just the first of many FACTS that the woolly-left have been ignoring for many years now",
        "It is only a matter of time before race riots spill blood on our streets",
        "Why did nobody listen to Enoch Powell all those years ago?",
        ":]",
        "Will sex with animals be legal next?",
        "Will sex with children be legal next?"
]

end_punctuation = [
    ".",
    "!",
    "!!",
    "!!!",
    "!!!",
    "!!!!!",
    "!?!",
    "!??"
]

# Actual code starts here, oh my goooooooooo
rnd = random.randint
choice = random.choice

def getPunctuation():
    r = rnd(0,5)

    if(r  < 2):
        return ". "
    if(r == 3 or 4):
        return ", "
    if(r == 5):
        return "... "
    return ",, "

def createIdiot(user=None):
    
    if user is "":
        idiotText = choice(opening2) + " " + choice(hated_object) + " " + choice(terrible_thing)
    else:
        idiotText = choice(opening2) + " " + user + " is" + " " + choice(terrible_thing)
    if(rnd(0,1) == 0):
        idiotText += " because " + choice(because);
    idiotText += getPunctuation() + " " + choice(moronic_solution) + getPunctuation()
    if(rnd(0,5) < 2):
        idiotText += choice(signoff) + choice(end_punctuation)
    else:
        idiotText = choice(opening1) + getPunctuation() + idiotText + getPunctuation()

    if(rnd(0,3) > 1):
        idiotText = idiotText.upper()

    return idiotText
  
@hook.command
def hys(inp):
    try:
        #forces things into string...i think??
        input = str(inp)
    except:
        input = ""
    return createIdiot(input)



